# Generated by Django 3.2.13 on 2023-03-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Id',
            new_name='ID',
        ),
    ]
