# Generated by Django 3.2.13 on 2023-03-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemon', '0002_rename_id_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ID',
            new_name='booking_identity',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='Id',
            new_name='menu_identity',
        ),
    ]
